name: sohoz_park
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_svg: 2.0.9
  google_fonts: 6.1.0

  flutter_easyloading: ^3.0.5
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  get_storage: ^2.1.1
  fluttertoast: ^8.2.4
  flutter: 
    sdk: flutter
  qr_code_scanner: ^1.0.1
  intl: ^0.19.0
#  flutter_pax_printer_utility: ^0.1.3
  path_provider: ^2.1.2
  screenshot: ^2.1.0
  path: ^1.8.3
  sunmi_printer_plus: ^2.1.2
  dropdown_button2: ^2.3.9
  workmanager: ^0.5.2



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

